//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOAdmiral
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blacklist
    {
        public int BlacklistVisitorID { get; set; }
        public int BlacklistRejectionName { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
