//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOAdmiral
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class User19_11_SecurityEntities : DbContext
    {
        public User19_11_SecurityEntities()
            : base("name=User19_11_SecurityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blacklist> Blacklist { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Reason> Reason { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<Visit> Visit { get; set; }
        public virtual DbSet<Visitor> Visitor { get; set; }
    }
}
