//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOOAdmiral
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visitor()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int VisitorID { get; set; }
        public string VisitorPhone { get; set; }
        public string VisitorEmail { get; set; }
        public string VisitorOrganization { get; set; }
        public string VisitorNote { get; set; }
        public System.DateTime VisitorBirthday { get; set; }
        public int VisitorPassportNumber { get; set; }
        public string VisitorName { get; set; }
        public int VisitorPassportSeria { get; set; }
    
        public virtual Blacklist Blacklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
